open_weather_map:
  options:
    attribution: 'Map data &copy; <a href="http://openweathermap.org">OpenWeatherMap</a>'
    opacity: 0.5
  variants:
    clouds:
      url: 'http://{s}.tile.openweathermap.org/map/clouds/{z}/{x}/{y}.png'
    clouds_classic:
      url: 'http://{s}.tile.openweathermap.org/map/clouds_cls/{z}/{x}/{y}.png'
    precipitation:
      url: 'http://{s}.tile.openweathermap.org/map/precipitation/{z}/{x}/{y}.png'
    precipitation_classic:
      url: 'http://{s}.tile.openweathermap.org/map/precipitation_cls/{z}/{x}/{y}.png'
    rain:
      url: 'http://{s}.tile.openweathermap.org/map/rain/{z}/{x}/{y}.png'
    rain_classic:
      url: 'http://{s}.tile.openweathermap.org/map/rain_cls/{z}/{x}/{y}.png'
    pressure:
      url: 'http://{s}.tile.openweathermap.org/map/pressure/{z}/{x}/{y}.png'
    pressure_contour:
      url: 'http://{s}.tile.openweathermap.org/map/pressure_cntr/{z}/{x}/{y}.png'
    wind:
      url: 'http://{s}.tile.openweathermap.org/map/wind/{z}/{x}/{y}.png'
    temperature:
      url: 'http://{s}.tile.openweathermap.org/map/temp/{z}/{x}/{y}.png'
    snow:
      url: 'http://{s}.tile.openweathermap.org/map/snow/{z}/{x}/{y}.png'

stamen:
  options:
    attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
    subdomains: 'abcd'
    min_zoom: 0
    max_zoom: 20
  variants:
    toner_hybrid:
      url: 'http://{s}.tile.stamen.com/toner-hybrid/{z}/{x}/{y}.png'
    toner_lines:
      url: 'http://{s}.tile.stamen.com/toner-lines/{z}/{x}/{y}.png'
    toner_labels:
      url: 'http://{s}.tile.stamen.com/toner-labels/{z}/{x}/{y}.png'


open_map_surfer:
  url: 'http://korona.geog.uni-heidelberg.de/tiles/roads/x={x}&y={y}&z={z}'
  options:
    attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
  variants:
    admin_bounds:
      url: 'http://korona.geog.uni-heidelberg.de/tiles/adminb/x={x}&y={y}&z={z}'